### YamlMime:ApiPage
title: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Graphic
body:
- api1: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Graphic
  id: Alis_Builder_Core_Ecs_System_ConfigurationBuilders_Graphic
  metadata:
    uid: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Graphic
    commentId: N:Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Graphic
- h3: Classes
- parameters:
  - type:
      text: GraphicSettingBuilder
      url: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Graphic.GraphicSettingBuilder.html
    description: The graphic setting builder class
languageId: csharp
