### YamlMime:ApiPage
title: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Audio
body:
- api1: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Audio
  id: Alis_Builder_Core_Ecs_System_ConfigurationBuilders_Audio
  metadata:
    uid: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Audio
    commentId: N:Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Audio
- h3: Classes
- parameters:
  - type:
      text: AudioSettingBuilder
      url: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.Audio.AudioSettingBuilder.html
    description: The audio setting builder class
languageId: csharp
