### YamlMime:ApiPage
title: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.General
body:
- api1: Namespace Alis.Builder.Core.Ecs.System.ConfigurationBuilders.General
  id: Alis_Builder_Core_Ecs_System_ConfigurationBuilders_General
  metadata:
    uid: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.General
    commentId: N:Alis.Builder.Core.Ecs.System.ConfigurationBuilders.General
- h3: Classes
- parameters:
  - type:
      text: GeneralSettingBuilder
      url: Alis.Builder.Core.Ecs.System.ConfigurationBuilders.General.GeneralSettingBuilder.html
    description: The general setting builder class
languageId: csharp
